# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180308_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surface',
            field=models.ImageField(default='image/default_surface.jpg', upload_to='image/%Y/%m'),
        ),
    ]
