# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标签'),
        ),
    ]
